# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d58dc6a112c6982d820a83689fe66227657b2f8d808f4bc3b6addce8a6273f5009f6974c4eae82c0d0975f7c4e3fe4ddf151b8e150d499e5cfbd6f714a2f08

test:
  secret_key_base: d680f314dd74e4b2e7f6995a6020bced6ccdc1d4c6a8edda75d6faf22057dd99bee099f6390270ac3ea6c5f9435fb4a27dd0da199568238d8bb51abe97b9baf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
